apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-kube-cloud-credentials-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-kube-cloud-credentials-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-kube-cloud-credentials-operator
  template:
    metadata:
      labels:
        app: vault-kube-cloud-credentials-operator
    spec:
      serviceAccountName: vault-kube-cloud-credentials-operator
      containers:
        - name: vault-kube-cloud-credentials-operator
          image: quay.io/utilitywarehouse/vault-kube-cloud-credentials:0.8.3
          args:
            - operator
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              cpu: 500m
              memory: 200Mi
